### ISSUE TITLE
Right shift not working

### ISSUE THREAD

**Issue by costin88boss** [DasJNNJ/CrabGame-Cheat#10]
it doesn't open anything, but it tells me that in the menu.

**Comment by nusiiij** [comment]
i've already opened a pr (pull request), which would fix all of the problems, and add an item spawner, Just wait for DasJNNJ to accept it/fix it himself and it'll work again, it shouldn't take too long

**Comment by costin88boss** [comment]
Ok, please notify me when it’s updated by replying.

**Comment by costin88boss** [comment]
> i've already opened a pr (pull request), which would fix all of the problems, and add an item spawner, Just wait for DasJNNJ to accept it/fix it himself and it'll work again, it shouldn't take too long

can you give me the dll file you have? i don't want to wait anymore

**Comment by nusiiij** [comment]
> 
> 
> > i've already opened a pr (pull request), which would fix all of the problems, and add an item spawner, Just wait for DasJNNJ to accept it/fix it himself and it'll work again, it shouldn't take too long
> 
> can you give me the dll file you have? i don't want to wait anymore

it's fixed
