### ISSUE TITLE
failed to load assembly

### ISSUE THREAD

**Issue by dougstar03** [DasJNNJ/CrabGame-Cheat#3]
after completing all the setup, i put the CrabGame_Cheat_BepInEx.dll file in the plugins folder and load the game, however, melonloader returns the following error:

[08:40:19.443] [ERROR] Failed to Load Assembly for D:\Steam\steamapps\common\Crab Game\Plugins\CrabGame_Cheat_BepInEx.dll: No Compatibility Layer Found!

and loads without the plugin, however, the menu GUI still loads and some of the features work, but when I try to use glass break esp, for example, it breaks everything.

**Comment by DasJNNJ** [comment]
I know that GlassBreak is an issue, it should be fixed in the next version.
