### ISSUE TITLE
Adding Give Weapons

### ISSUE THREAD

**Issue by h4Ck3D001** [DasJNNJ/CrabGame-Cheat#4]
You could add a feature like give weapons. It should work with this:
PlayerInventory.Instance.ForceGiveItem(ItemManager.GetItemById(1));
Just replace the ID (1) with the right ID for the right thing, maybe you could test the IDs, I don't really know what weapon has what ID.

**Comment by DasJNNJ** [comment]
Yes I know that, I had that feature already but removed it due to the weapons not working. Also in the newest Version of CrabGame there is a Check for a Riffle and Double Barrel which bans you.
